/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 22 17:05:48 KST 2017
 */

package com.sleepycat.util;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class ExceptionUnwrapper_ESTest4 extends ExceptionUnwrapper_ESTest_scaffolding4 {


  @Test
  public void test1()  throws Throwable  {
      Exception exception0 = new Exception();
      RuntimeExceptionWrapper runtimeExceptionWrapper0 = new RuntimeExceptionWrapper((Throwable) exception0);
      Exception exception1 = (Exception)ExceptionUnwrapper.unwrapAny(runtimeExceptionWrapper0);
      assertEquals("java.lang.Exception", exception1.toString());
  }

  @Test
  public void test3()  throws Throwable  {
      Exception exception0 = new Exception();
      Exception exception1 = ExceptionUnwrapper.unwrap(exception0);
      assertSame(exception1, exception0);
  }


}
