/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 07 10:35:27 KST 2017
 */

package org.prevayler.foundation;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class Cool_ESTest4 extends Cool_ESTest_scaffolding4 {


  @Test
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        Cool.sleep((-3405L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // timeout value is negative
         //
         assertThrownBy("java.lang.Thread", e);
      }
  }



  @Test
  public void test4()  throws Throwable  {
      Cool cool0 = new Cool();
      Exception exception0 = new Exception("Unexpected Exception was thrown.");
      // Undeclared exception!
      try { 
        Cool.unexpected(exception0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unexpected Exception was thrown.
         //
         assertThrownBy("org.prevayler.foundation.Cool", e);
      }
  }

  @Test
  public void test5()  throws Throwable  {
      Cool.sleep(205L);
  }
}
